name: promad_sora
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  intro_slider: ^4.2.1
  flutter_screenutil: ^5.9.0
  material_design_icons_flutter: ^7.0.7296
  stylish_bottom_bar: ^1.0.3
  simple_gradient_text: ^1.3.0
  font_awesome_flutter: ^10.7.0
  flutter_facebook_auth: ^6.2.0
  lottie: ^3.1.0
  dropdown_button2: ^2.3.9
  google_sign_in: ^6.2.1
  fluttertoast: ^8.2.5
  flutter_stripe: ^10.1.1
  twitter_login: ^4.4.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/lottie/

  fonts:
    - family: Nexa_Regular
      fonts:
        - asset: assets/font/Nexa-Trial-Regular.otf
    - family: Nexa_Heavy
      fonts:
        - asset: assets/font/Nexa-Trial-Heavy.otf
    - family: Nexa_Bold
      fonts:
        - asset: assets/font/Nexa-Trial-Bold.otf
    - family: Nexa_Light
      fonts:
        - asset: assets/font/Nexa-Trial-Light.otf